version: '3'

services:
  thredds-quickstart:
    image: "unidata/thredds-docker:${VERSION}"
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"

  thredds-production:
    image: "unidata/thredds-docker:${VERSION}"
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
        #      - /${PWD}/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ${PWD}/files/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - ${PWD}/files/wmsConfig.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml
      - ${PWD}/files/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ${PWD}/files/enhancedCatalog.xml:/usr/local/tomcat/content/thredds/enhancedCatalog.xml
      - ${PWD}/files/gbr1_2.0catalog.xml:/usr/local/tomcat/content/thredds/gbr1_2.0catalog.xml
      # data files
        #      - /${PWD}/thredds:/usr/local/tomcat/content/thredds
      - ${PWD}/data:/usr/local/tomcat/content/thredds/public
      - /OSM/MEL/OA_EREEFS_DEV1/work/fx3/:/usr/local/tomcat/content/thredds/public/fx3
      # cache files
      - /OSM/MEL/OA_EREEFS_DEV1/scratch/tmp:/usr/local/tomcat/content/thredds/cache
      # logs
            #- ${PWD}/tomcat-logs/:/usr/local/tomcat/logs/
            #- ${PWD}/thredds-logs/:/usr/local/tomcat/content/thredds/logs/
      - /OSM/MEL/OA_EREEFS_DEV1/scratch/logs/tomcat:/usr/local/tomcat/logs/
      - /OSM/MEL/OA_EREEFS_DEV1/scratch/logs/:/usr/local/tomcat/content/thredds/logs/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

  tdm:
    image: unidata/tdm-docker:4.6
    container_name: tdm
    volumes:
      - /${PWD}/thredds/directory:/usr/local/tomcat/content/thredds
      - /${PWD}/data/tdm:/${PWD}/data/tdm
      # TDM logging non-configurable until 5.0 so you'll need tdm.sh and
      # tdm.jar if you want to log outside the container :-(
      - /${PWD}/tdm/logs:/usr/local/tomcat/content/tdm/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
