version: '3'

services:
  thredds-quickstart:
    image: "unidata/thredds-docker:${VERSION}"
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"

  thredds-production:
    image: "unidata/thredds-docker:${VERSION}"
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - /home/debian/src/thredds-docker/tomcat/logs/:/usr/local/tomcat/logs/
      - /home/debian/src/thredds-docker/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
        #      - /home/debian/src/thredds-docker/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - /home/debian/src/thredds-docker/files/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - /home/debian/src/thredds-docker/files/wmsConfig.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml
      - /home/debian/src/thredds-docker/files/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - /home/debian/src/thredds-docker/files/enhancedCatalog.xml:/usr/local/tomcat/content/thredds/enhancedCatalog.xml
      - /home/debian/src/thredds-docker/thredds:/usr/local/tomcat/content/thredds
      - /home/debian/src/thredds-docker/data/sven:/usr/local/tomcat/content/thredds/public/sven
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

  tdm:
    image: unidata/tdm-docker:4.6
    container_name: tdm
    volumes:
      - /home/debian/src/thredds-docker/thredds/directory:/usr/local/tomcat/content/thredds
      - /home/debian/src/thredds-docker/data/tdm:/home/debian/src/thredds-docker/data/tdm
      # TDM logging non-configurable until 5.0 so you'll need tdm.sh and
      # tdm.jar if you want to log outside the container :-(
      - /home/debian/src/thredds-docker/tdm/logs:/usr/local/tomcat/content/tdm/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
